### ISSUE TITLE
Null reference when connection is remote closed

### ISSUE THREAD

**Issue by RomainDGx** [signature-opensource/CK-MQTT#37]
When I start my application that use a CK.MQTT.Client.MQTTClientAgent, it crashes with the following callstack:
![image](https://user-images.githubusercontent.com/45673753/210227162-02a077de-b698-4fdb-b31f-a4789fafbde0.png)

When I debug, the first error throws is a NullReferenceException.

To reproduce it, you must have at least 2 MQTT clients with the same clientId in parameter of MQTTClientCredentials. You should use "Just my Code" in Visual Studio.

**Comment by Kuinox** [comment]
Lots of refactoring around this area, bug report won't be relevent for new versions.
